# Generated by Django 3.0.3 on 2020-02-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=2)),
                ('ending_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_room', to=settings.AUTH_USER_MODEL)),
                ('starting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('starting_room', 'ending_room')},
            },
        ),
    ]
