# Generated by Django 3.0.3 on 2020-03-03 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('ending_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_room', to='rooms.Room')),
                ('starting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_room', to='rooms.Room')),
            ],
            options={
                'unique_together': {('starting_room', 'ending_room', 'direction')},
            },
        ),
    ]
