# Generated by Django 3.0.3 on 2020-02-29 21:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomdirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdirection',
            name='direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1),
        ),
        migrations.AlterField(
            model_name='roomdirection',
            name='ending_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_room', to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='roomdirection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomdirection',
            name='starting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_room', to='rooms.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='roomdirection',
            unique_together={('starting_room', 'ending_room', 'direction')},
        ),
    ]
